Write a python program to find the maximum weight in pounds from a given tuple weight_pounds.

weight_pounds = (173, 152, 205, 119, 250)

In [5]:
import numpy as np

# Create a 3x3 array with multiple values
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get the dimension of the array
dim = arr.ndim

# Get the size of the array
size = arr.size

# Get the shape of the array
shape = arr.shape

print("Array:\n", arr)
print("Dimension of the array:", dim)
print("Size of the array:", size)
print("Shape of the array:", shape)


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of the array: 2
Size of the array: 9
Shape of the array: (3, 3)
