# NumPy

NumPy (Numerical Python) is a popular Python library for scientific computing that provides powerful tools for working with arrays, matrices, and other numerical data. It is one of the fundamental libraries in the Python data science ecosystem, and is used extensively in fields such as machine learning, physics, engineering, finance, and more.

NumPy provides a high-performance multidimensional array object, which is the core data structure used in many numerical algorithms. The library also provides a wide range of mathematical functions for manipulating arrays and matrices, as well as tools for linear algebra, Fourier analysis, and random number generation.

Some of the key features of NumPy include:

* Fast and memory-efficient array processing
* Comprehensive array slicing and indexing capabilities
* Broadcasting functionality for performing element-wise operations on arrays with different shapes and sizes
* A powerful suite of linear algebra and statistical functions
* Compatibility with other Python libraries, such as SciPy, Pandas, and Matplotlib.
* NumPy is an open-source project that can be installed using pip, the standard package manager for Python. Once installed, NumPy can be imported into a Python script or interactive session using the import numpy statement.

- **Numerical python**
- Geometrical, calculus, arithmatic
- Collection of similar classes
- Classes are collection of similar variables and methods
- Performing numerical operations in python


- **Saving Code time**
- **No for loops**
- **Faster Execution**
- **Uses less memory over list**

### Official link to numpy
https://numpy.org/doc/stable/user/absolute_beginners.html

## Installing libraries
#!pip install numpy

## Importing libraries

- We can not just import libraries and call them directly as some libraries names are big
- Hence, we use alias such as np for numpy (conventional way)

In [ ]:
# Importing numpy library
import numpy as np

## Data structures
- Scalar
- Vector
- Arrays 
- Matrix (built in)



#### Number of dimensions (a.ndim)
- The number of dimensions is the rank of array

#### Shape of an array (a.shape)
- The shape of any array is tuple of integers giving the size of the array along each dimension.

#### Size of an array (a.size)
- how many values there are in the array using the size attribute

#### Arrays:
- A numpy Array is a collection of common type of data structures having elements with same data type. 
- It is indexed by a tuple of non-negative integers.
- It is used to store collections of data. 
- In Python programming, an arrays are handled by the “array” module. 
- If you create arrays using the array module, elements of the array must be of the same data type.

NumPy is used for working with an array.

### Scalar

In [ ]:
a_scalar = np.array(5) # creating an np array
print(a_scalar) # printing the result

5


#### Explanation:
- The code creates a NumPy array called a with a single scalar element of value 5.

In [ ]:
a_scalar.ndim # number of dimensions

0

#### Explanation:
The result of calling np.array(5) is a 0-dimensional array, also known as a scalar or a rank-0 array. This is because the input argument is a single value, not a sequence of values.

In [ ]:
a_scalar.shape # shape of variable a_scalar

()

In [ ]:
a_scalar.size # size of variable a_scalar

1

#### Explanation:
The shape attribute of a is called using the syntax a.shape. Since a is a scalar array, its shape is an empty tuple ().

### Initializing a numpy array
- We can initialize numpy arrays from nested Python lists, and access elements using square bracktes.

### Vector

In NumPy, a vector is typically represented as a 1-dimensional array. A 1D NumPy array can be created using the np.array() function and passing in a list or tuple of values

### Transposing a vector

In [ ]:
a = np.array([[1, 2, 3]])
print(a.T) # T is used to transpose the vector

[[1]
 [2]
 [3]]


### Matrix

In Numpy, a matrix is represented as a two-dimensional array. You can create a matrix in Numpy by simply passing a list of lists to the numpy.array() function. 

### linspace()
linspace is a NumPy function that is used to create a 1-dimensional array of equally spaced numbers within a specified range. The function takes three arguments: 
<br>
<br>
**np.linspace(start, stop, num)**
<br>
<br>
**start**: The starting value of the sequence.
<br>
**stop**: The end value of the sequence.
<br>
**num**: The number of evenly spaced numbers to generate between start and stop, inclusive.

Note that linspace is similar to the arange function, but the main difference is that arange generates numbers with a step size between them, while linspace generates numbers with a fixed number of points within the range.

## Basic mathematics in numpy


### Addition:
- add multiple arrays either using **(x + y)** or **np.sum(x, y)** or **np.add(x, y)**

### Subtraction
- subtract multiple arrays either using **(x - y)** or **np.subtract(x, y)** 

### Multiplication
Multiply multiple arrays either using **(x * y)** or **np.multiply(x, y)** 

### Divison
Divide multiple arrays either using **(x/y)** or **np.divide(x, y)**

### Multidimension arrays
Same approach can by used multidimension array.
<br>
Axis can be defined to add them by either row wise (axis = 0) or column wise (axis = 1). 
<br>
If no axis defined, it will add all elements together.


### Basic mathematics with multiple arrays
When we add, subtract, multiply and divide multiple arrays, they perform maths element wise.

In [ ]:
# multiply arrays
a = np.array([2,3,4]) 
b = np.array([5,6,3])
np.multiply(a,b) # element wise multiplication

array([10, 18, 12])

In [ ]:
print(a * b)

[10 18 12]


### Other mathematical functions

In [ ]:
# exp, sqrt
a=[1,2,4]
print(np.exp(a))
print(np.sqrt(a))

[ 2.71828183  7.3890561  54.59815003]
[1.         1.41421356 2.        ]


### Statistical functions
We can simply perform basic descriptive statistics analysis such as:
<br>
**mean**: np.mean(a)
<br>
**median**: np.median(a)
<br>
**var**: np.var(a) for population and **np.var(a, ddof = 1)** for sample
<br>
**std**: np.std(a) for population and **np.std(a, ddof = 1)** for sample
<br>
**mode**: st.mode(a) from scipy library

#### Using multidimensional array to perform basic descriptive statistics

In [ ]:
a = np.array([[1, 6, 7],
[4, 3, 9]])
print(a)


[[1 6 7]
 [4 3 9]]


In [ ]:
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))
print('Mean :',np.mean(a,axis=0))
print('Mean :',np.mean(a,axis=1))
print('Median :',np.median(a,axis=1))
print('Median :',np.median(a,axis=0))

Min : [1 3 7]
Max : [7 9]
Mean : [2.5 4.5 8. ]
Mean : [4.66666667 5.33333333]
Median : [6. 4.]
Median : [2.5 4.5 8. ]


### Dot product
In NumPy, the dot product of two arrays can be computed using the **numpy.dot(a, b)** function or **a.dot(b)**.

### Dot product between a scalar and a vector. 

In [ ]:
a = np.array([1, 2, 3])
b = 2

dot_product = np.dot(a, b)
print("Dot product:", dot_product)

Dot product: [2 4 6]


In [ ]:
dot_product = a.dot(b)
print("Dot product:", dot_product)

Dot product: [2 4 6]


## Slicing an array
- NumPy arrays can be sliced similar to python list
- Since arrays are multidimensional, we must have to specify a slice for each dimension of the array.
- [row, column]
- [ : , : ] means all rows and all columns.
- [0,0] means first element of a multidimensional array

In [ ]:
# to slice arrays based on arrays
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Creating an array containing only first row.

In [ ]:
a[0]

array([1, 2, 3])

## Boolean array indexing
- It lets us to pick out arbitrary  elements of an array
- Used to pick the element of an array that satisfy some condition

In [ ]:
a = np.array([[1, 2], [3, 1], [5, 6]])
a > 2

array([[False, False],
       [ True, False],
       [ True,  True]])

### Reshaping an array

In [ ]:
a = np.arange(16)
print(a)
array = np.arange(16).reshape(4, 4) # reshaping it into 2 columns 4 rows
array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a = np.array([[2,3,4],[4,5,6]])
print(a)

[[2 3 4]
 [4 5 6]]


In [ ]:
a.shape=(3,2)
print(a)

[[2 3]
 [4 4]
 [5 6]]


### Splitting the array

In [ ]:
# split the same array horiz - after 2 cols
x = np.arange(16).reshape(4,4)
print(x, "\n\n")
np.hsplit(x,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 




[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### sort
Numpy provides several functions to sort arrays and matrices

In [ ]:
a = np.array([1,4,2,5,3,6,8,7,9])
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[5,6,7,4],
              [9,2,3,7]])# sort along the column

print(a)

[[5 6 7 4]
 [9 2 3 7]]


In [ ]:
print(np.sort(a, axis=1))

[[4 5 6 7]
 [2 3 7 9]]


### Identity matrix

- An identity matrix is a square matrix where all the diagonal elements are 1 and all other elements are 0. In Numpy, you can create an identity matrix using the **numpy.identity()** or **np.eye()** function. Here's an example:

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### fliping an array

In [ ]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print(a)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(np.flip(a,axis=1))


[[ 5  4  3  2  1]
 [10  9  8  7  6]]


## broadcasting
 - the ability of NumPy to treat arrays of different shapes during arithmetic operations

In [ ]:
a = np.array([[1,1,1],[10,10,10],[20,20,20],[30,30,30]])
b = np.array([1, 2, 3])
print(a)
print(b)


[[ 1  1  1]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[1 2 3]


In [ ]:
print(a.shape)
print(b.shape)


(4, 3)
(3,)


In [ ]:
print('First array: \n',a,'\n')
print('Second array: \n',b,'\n')

print(a+b)

First array: 
 [[ 1  1  1]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

Second array: 
 [1 2 3] 

[[ 2  3  4]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


## Stacking

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 11, 12, 13])


In [ ]:
print(np.vstack((a, b))) # vertical stacking

[[ 1  2  3  4]
 [10 11 12 13]]


In [ ]:
print(np.hstack((a, b))) # horizontal stacking

[ 1  2  3  4 10 11 12 13]
